# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  python-docker:
    parameters:
      python-version:
        description: "python version"
        default: "3.9"
        type: string
    docker:
      - image: cimg/python:<<parameters.python-version>>

jobs:
  build_wheel:
    parameters:
      python-version:
        description: "python version"
        default: "3.9"
        type: string
    executor:
      name: python-docker
      python-version: <<parameters.python-version>>
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y cxxtest
      - run: make install-prereqs
      - run: make test
      - run: make pytest
      - run: make pymodule
      - run: make wheel
      - store_artifacts:
          path: dist
  build_sdist:
    parameters:
      python-version:
        description: "python version"
        default: "3.9"
        type: string
    executor:
      name: python-docker
      python-version: <<parameters.python-version>>
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y cxxtest
      - run: make install-prereqs
      - run: make test
      - run: make pytest
      - run: make pymodule
      - run: make sdist
      - store_artifacts:
          path: dist

workflows:
  matrix-build:
    jobs:
      - build_wheel:
          matrix:
            parameters:
              python-version:
                - "3.9"
                - "3.8"
                - "3.7"
                - "3.6"
      - build_sdist