# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y install cxxtest
      - run: make install-prereqs
      - run: make test
      - run: make pytest
      - run: make pymodule
      - run: make sdist